// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientSecret applies equality check predicate on the "client_secret" field. It's identical to ClientSecretEQ.
func ClientSecret(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecret, v))
}

// RedirectUris applies equality check predicate on the "redirect_uris" field. It's identical to RedirectUrisEQ.
func RedirectUris(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRedirectUris, v))
}

// AllowLocalhost applies equality check predicate on the "allow_localhost" field. It's identical to AllowLocalhostEQ.
func AllowLocalhost(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAllowLocalhost, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldEnabled, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRemark, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldName, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretEQ applies the EQ predicate on the "client_secret" field.
func ClientSecretEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecret, v))
}

// ClientSecretNEQ applies the NEQ predicate on the "client_secret" field.
func ClientSecretNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientSecret, v))
}

// ClientSecretIn applies the In predicate on the "client_secret" field.
func ClientSecretIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientSecret, vs...))
}

// ClientSecretNotIn applies the NotIn predicate on the "client_secret" field.
func ClientSecretNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientSecret, vs...))
}

// ClientSecretGT applies the GT predicate on the "client_secret" field.
func ClientSecretGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientSecret, v))
}

// ClientSecretGTE applies the GTE predicate on the "client_secret" field.
func ClientSecretGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientSecret, v))
}

// ClientSecretLT applies the LT predicate on the "client_secret" field.
func ClientSecretLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientSecret, v))
}

// ClientSecretLTE applies the LTE predicate on the "client_secret" field.
func ClientSecretLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientSecret, v))
}

// ClientSecretContains applies the Contains predicate on the "client_secret" field.
func ClientSecretContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientSecret, v))
}

// ClientSecretHasPrefix applies the HasPrefix predicate on the "client_secret" field.
func ClientSecretHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientSecret, v))
}

// ClientSecretHasSuffix applies the HasSuffix predicate on the "client_secret" field.
func ClientSecretHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientSecret, v))
}

// ClientSecretEqualFold applies the EqualFold predicate on the "client_secret" field.
func ClientSecretEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientSecret, v))
}

// ClientSecretContainsFold applies the ContainsFold predicate on the "client_secret" field.
func ClientSecretContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientSecret, v))
}

// RedirectUrisEQ applies the EQ predicate on the "redirect_uris" field.
func RedirectUrisEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRedirectUris, v))
}

// RedirectUrisNEQ applies the NEQ predicate on the "redirect_uris" field.
func RedirectUrisNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRedirectUris, v))
}

// RedirectUrisIn applies the In predicate on the "redirect_uris" field.
func RedirectUrisIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRedirectUris, vs...))
}

// RedirectUrisNotIn applies the NotIn predicate on the "redirect_uris" field.
func RedirectUrisNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRedirectUris, vs...))
}

// RedirectUrisGT applies the GT predicate on the "redirect_uris" field.
func RedirectUrisGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRedirectUris, v))
}

// RedirectUrisGTE applies the GTE predicate on the "redirect_uris" field.
func RedirectUrisGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRedirectUris, v))
}

// RedirectUrisLT applies the LT predicate on the "redirect_uris" field.
func RedirectUrisLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRedirectUris, v))
}

// RedirectUrisLTE applies the LTE predicate on the "redirect_uris" field.
func RedirectUrisLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRedirectUris, v))
}

// RedirectUrisContains applies the Contains predicate on the "redirect_uris" field.
func RedirectUrisContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldRedirectUris, v))
}

// RedirectUrisHasPrefix applies the HasPrefix predicate on the "redirect_uris" field.
func RedirectUrisHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldRedirectUris, v))
}

// RedirectUrisHasSuffix applies the HasSuffix predicate on the "redirect_uris" field.
func RedirectUrisHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldRedirectUris, v))
}

// RedirectUrisEqualFold applies the EqualFold predicate on the "redirect_uris" field.
func RedirectUrisEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldRedirectUris, v))
}

// RedirectUrisContainsFold applies the ContainsFold predicate on the "redirect_uris" field.
func RedirectUrisContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldRedirectUris, v))
}

// AllowLocalhostEQ applies the EQ predicate on the "allow_localhost" field.
func AllowLocalhostEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAllowLocalhost, v))
}

// AllowLocalhostNEQ applies the NEQ predicate on the "allow_localhost" field.
func AllowLocalhostNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldAllowLocalhost, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldEnabled, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.NotPredicates(p))
}
