// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the checkinrecord type in the database.
	Label = "checkin_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCheckinDate holds the string denoting the checkin_date field in the database.
	FieldCheckinDate = "checkin_date"
	// FieldAmountAwarded holds the string denoting the amount_awarded field in the database.
	FieldAmountAwarded = "amount_awarded"
	// FieldStreakDays holds the string denoting the streak_days field in the database.
	FieldStreakDays = "streak_days"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the checkinrecord in the database.
	Table = "checkin_records"
)

// Columns holds all SQL columns for checkinrecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCheckinDate,
	FieldAmountAwarded,
	FieldStreakDays,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CheckinDateValidator is a validator for the "checkin_date" field. It is called by the builders before save.
	CheckinDateValidator func(string) error
	// DefaultStreakDays holds the default value on creation for the "streak_days" field.
	DefaultStreakDays int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CheckinRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCheckinDate orders the results by the checkin_date field.
func ByCheckinDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinDate, opts...).ToFunc()
}

// ByAmountAwarded orders the results by the amount_awarded field.
func ByAmountAwarded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountAwarded, opts...).ToFunc()
}

// ByStreakDays orders the results by the streak_days field.
func ByStreakDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreakDays, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
