// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldUserID, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCheckinDate, v))
}

// AmountAwarded applies equality check predicate on the "amount_awarded" field. It's identical to AmountAwardedEQ.
func AmountAwarded(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldAmountAwarded, v))
}

// StreakDays applies equality check predicate on the "streak_days" field. It's identical to StreakDaysEQ.
func StreakDays(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldStreakDays, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldUserID, v))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldCheckinDate, v))
}

// CheckinDateContains applies the Contains predicate on the "checkin_date" field.
func CheckinDateContains(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldContains(FieldCheckinDate, v))
}

// CheckinDateHasPrefix applies the HasPrefix predicate on the "checkin_date" field.
func CheckinDateHasPrefix(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldHasPrefix(FieldCheckinDate, v))
}

// CheckinDateHasSuffix applies the HasSuffix predicate on the "checkin_date" field.
func CheckinDateHasSuffix(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldHasSuffix(FieldCheckinDate, v))
}

// CheckinDateEqualFold applies the EqualFold predicate on the "checkin_date" field.
func CheckinDateEqualFold(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEqualFold(FieldCheckinDate, v))
}

// CheckinDateContainsFold applies the ContainsFold predicate on the "checkin_date" field.
func CheckinDateContainsFold(v string) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldContainsFold(FieldCheckinDate, v))
}

// AmountAwardedEQ applies the EQ predicate on the "amount_awarded" field.
func AmountAwardedEQ(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldAmountAwarded, v))
}

// AmountAwardedNEQ applies the NEQ predicate on the "amount_awarded" field.
func AmountAwardedNEQ(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldAmountAwarded, v))
}

// AmountAwardedIn applies the In predicate on the "amount_awarded" field.
func AmountAwardedIn(vs ...float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldAmountAwarded, vs...))
}

// AmountAwardedNotIn applies the NotIn predicate on the "amount_awarded" field.
func AmountAwardedNotIn(vs ...float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldAmountAwarded, vs...))
}

// AmountAwardedGT applies the GT predicate on the "amount_awarded" field.
func AmountAwardedGT(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldAmountAwarded, v))
}

// AmountAwardedGTE applies the GTE predicate on the "amount_awarded" field.
func AmountAwardedGTE(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldAmountAwarded, v))
}

// AmountAwardedLT applies the LT predicate on the "amount_awarded" field.
func AmountAwardedLT(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldAmountAwarded, v))
}

// AmountAwardedLTE applies the LTE predicate on the "amount_awarded" field.
func AmountAwardedLTE(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldAmountAwarded, v))
}

// StreakDaysEQ applies the EQ predicate on the "streak_days" field.
func StreakDaysEQ(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldStreakDays, v))
}

// StreakDaysNEQ applies the NEQ predicate on the "streak_days" field.
func StreakDaysNEQ(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldStreakDays, v))
}

// StreakDaysIn applies the In predicate on the "streak_days" field.
func StreakDaysIn(vs ...int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldStreakDays, vs...))
}

// StreakDaysNotIn applies the NotIn predicate on the "streak_days" field.
func StreakDaysNotIn(vs ...int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldStreakDays, vs...))
}

// StreakDaysGT applies the GT predicate on the "streak_days" field.
func StreakDaysGT(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldStreakDays, v))
}

// StreakDaysGTE applies the GTE predicate on the "streak_days" field.
func StreakDaysGTE(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldStreakDays, v))
}

// StreakDaysLT applies the LT predicate on the "streak_days" field.
func StreakDaysLT(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldStreakDays, v))
}

// StreakDaysLTE applies the LTE predicate on the "streak_days" field.
func StreakDaysLTE(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldStreakDays, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckinRecord) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckinRecord) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckinRecord) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.NotPredicates(p))
}
