// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CheckinRecordUpdate is the builder for updating CheckinRecord entities.
type CheckinRecordUpdate struct {
	config
	hooks    []Hook
	mutation *CheckinRecordMutation
}

// Where appends a list predicates to the CheckinRecordUpdate builder.
func (_u *CheckinRecordUpdate) Where(ps ...predicate.CheckinRecord) *CheckinRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckinRecordUpdate) SetUserID(v int64) *CheckinRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableUserID(v *int64) *CheckinRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CheckinRecordUpdate) AddUserID(v int64) *CheckinRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinRecordUpdate) SetCheckinDate(v string) *CheckinRecordUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableCheckinDate(v *string) *CheckinRecordUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetAmountAwarded sets the "amount_awarded" field.
func (_u *CheckinRecordUpdate) SetAmountAwarded(v float64) *CheckinRecordUpdate {
	_u.mutation.ResetAmountAwarded()
	_u.mutation.SetAmountAwarded(v)
	return _u
}

// SetNillableAmountAwarded sets the "amount_awarded" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableAmountAwarded(v *float64) *CheckinRecordUpdate {
	if v != nil {
		_u.SetAmountAwarded(*v)
	}
	return _u
}

// AddAmountAwarded adds value to the "amount_awarded" field.
func (_u *CheckinRecordUpdate) AddAmountAwarded(v float64) *CheckinRecordUpdate {
	_u.mutation.AddAmountAwarded(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckinRecordUpdate) SetStreakDays(v int) *CheckinRecordUpdate {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableStreakDays(v *int) *CheckinRecordUpdate {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckinRecordUpdate) AddStreakDays(v int) *CheckinRecordUpdate {
	_u.mutation.AddStreakDays(v)
	return _u
}

// Mutation returns the CheckinRecordMutation object of the builder.
func (_u *CheckinRecordUpdate) Mutation() *CheckinRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckinRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckinRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinRecordUpdate) check() error {
	if v, ok := _u.mutation.CheckinDate(); ok {
		if err := checkinrecord.CheckinDateValidator(v); err != nil {
			return &ValidationError{Name: "checkin_date", err: fmt.Errorf(`ent: validator failed for field "CheckinRecord.checkin_date": %w`, err)}
		}
	}
	return nil
}

func (_u *CheckinRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckinDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountAwarded(); ok {
		_spec.SetField(checkinrecord.FieldAmountAwarded, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountAwarded(); ok {
		_spec.AddField(checkinrecord.FieldAmountAwarded, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckinRecordUpdateOne is the builder for updating a single CheckinRecord entity.
type CheckinRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckinRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *CheckinRecordUpdateOne) SetUserID(v int64) *CheckinRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableUserID(v *int64) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CheckinRecordUpdateOne) AddUserID(v int64) *CheckinRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinRecordUpdateOne) SetCheckinDate(v string) *CheckinRecordUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableCheckinDate(v *string) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetAmountAwarded sets the "amount_awarded" field.
func (_u *CheckinRecordUpdateOne) SetAmountAwarded(v float64) *CheckinRecordUpdateOne {
	_u.mutation.ResetAmountAwarded()
	_u.mutation.SetAmountAwarded(v)
	return _u
}

// SetNillableAmountAwarded sets the "amount_awarded" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableAmountAwarded(v *float64) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetAmountAwarded(*v)
	}
	return _u
}

// AddAmountAwarded adds value to the "amount_awarded" field.
func (_u *CheckinRecordUpdateOne) AddAmountAwarded(v float64) *CheckinRecordUpdateOne {
	_u.mutation.AddAmountAwarded(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckinRecordUpdateOne) SetStreakDays(v int) *CheckinRecordUpdateOne {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableStreakDays(v *int) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckinRecordUpdateOne) AddStreakDays(v int) *CheckinRecordUpdateOne {
	_u.mutation.AddStreakDays(v)
	return _u
}

// Mutation returns the CheckinRecordMutation object of the builder.
func (_u *CheckinRecordUpdateOne) Mutation() *CheckinRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the CheckinRecordUpdate builder.
func (_u *CheckinRecordUpdateOne) Where(ps ...predicate.CheckinRecord) *CheckinRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckinRecordUpdateOne) Select(field string, fields ...string) *CheckinRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckinRecord entity.
func (_u *CheckinRecordUpdateOne) Save(ctx context.Context) (*CheckinRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinRecordUpdateOne) SaveX(ctx context.Context) *CheckinRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckinRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinRecordUpdateOne) check() error {
	if v, ok := _u.mutation.CheckinDate(); ok {
		if err := checkinrecord.CheckinDateValidator(v); err != nil {
			return &ValidationError{Name: "checkin_date", err: fmt.Errorf(`ent: validator failed for field "CheckinRecord.checkin_date": %w`, err)}
		}
	}
	return nil
}

func (_u *CheckinRecordUpdateOne) sqlSave(ctx context.Context) (_node *CheckinRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckinRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinrecord.FieldID)
		for _, f := range fields {
			if !checkinrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckinDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountAwarded(); ok {
		_spec.SetField(checkinrecord.FieldAmountAwarded, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountAwarded(); ok {
		_spec.AddField(checkinrecord.FieldAmountAwarded, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	_node = &CheckinRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
