// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
)

// CheckinRecordCreate is the builder for creating a CheckinRecord entity.
type CheckinRecordCreate struct {
	config
	mutation *CheckinRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CheckinRecordCreate) SetUserID(v int64) *CheckinRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCheckinDate sets the "checkin_date" field.
func (_c *CheckinRecordCreate) SetCheckinDate(v string) *CheckinRecordCreate {
	_c.mutation.SetCheckinDate(v)
	return _c
}

// SetAmountAwarded sets the "amount_awarded" field.
func (_c *CheckinRecordCreate) SetAmountAwarded(v float64) *CheckinRecordCreate {
	_c.mutation.SetAmountAwarded(v)
	return _c
}

// SetStreakDays sets the "streak_days" field.
func (_c *CheckinRecordCreate) SetStreakDays(v int) *CheckinRecordCreate {
	_c.mutation.SetStreakDays(v)
	return _c
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableStreakDays(v *int) *CheckinRecordCreate {
	if v != nil {
		_c.SetStreakDays(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckinRecordCreate) SetCreatedAt(v time.Time) *CheckinRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableCreatedAt(v *time.Time) *CheckinRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CheckinRecordMutation object of the builder.
func (_c *CheckinRecordCreate) Mutation() *CheckinRecordMutation {
	return _c.mutation
}

// Save creates the CheckinRecord in the database.
func (_c *CheckinRecordCreate) Save(ctx context.Context) (*CheckinRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckinRecordCreate) SaveX(ctx context.Context) *CheckinRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckinRecordCreate) defaults() {
	if _, ok := _c.mutation.StreakDays(); !ok {
		v := checkinrecord.DefaultStreakDays
		_c.mutation.SetStreakDays(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkinrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckinRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CheckinRecord.user_id"`)}
	}
	if _, ok := _c.mutation.CheckinDate(); !ok {
		return &ValidationError{Name: "checkin_date", err: errors.New(`ent: missing required field "CheckinRecord.checkin_date"`)}
	}
	if v, ok := _c.mutation.CheckinDate(); ok {
		if err := checkinrecord.CheckinDateValidator(v); err != nil {
			return &ValidationError{Name: "checkin_date", err: fmt.Errorf(`ent: validator failed for field "CheckinRecord.checkin_date": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountAwarded(); !ok {
		return &ValidationError{Name: "amount_awarded", err: errors.New(`ent: missing required field "CheckinRecord.amount_awarded"`)}
	}
	if _, ok := _c.mutation.StreakDays(); !ok {
		return &ValidationError{Name: "streak_days", err: errors.New(`ent: missing required field "CheckinRecord.streak_days"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckinRecord.created_at"`)}
	}
	return nil
}

func (_c *CheckinRecordCreate) sqlSave(ctx context.Context) (*CheckinRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckinRecordCreate) createSpec() (*CheckinRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckinRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinrecord.Table, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(checkinrecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CheckinDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckinDate, field.TypeString, value)
		_node.CheckinDate = value
	}
	if value, ok := _c.mutation.AmountAwarded(); ok {
		_spec.SetField(checkinrecord.FieldAmountAwarded, field.TypeFloat64, value)
		_node.AmountAwarded = value
	}
	if value, ok := _c.mutation.StreakDays(); ok {
		_spec.SetField(checkinrecord.FieldStreakDays, field.TypeInt, value)
		_node.StreakDays = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkinrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinRecord.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinRecordCreate) OnConflict(opts ...sql.ConflictOption) *CheckinRecordUpsertOne {
	_c.conflict = opts
	return &CheckinRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinRecordCreate) OnConflictColumns(columns ...string) *CheckinRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinRecordUpsertOne{
		create: _c,
	}
}

type (
	// CheckinRecordUpsertOne is the builder for "upsert"-ing
	//  one CheckinRecord node.
	CheckinRecordUpsertOne struct {
		create *CheckinRecordCreate
	}

	// CheckinRecordUpsert is the "OnConflict" setter.
	CheckinRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CheckinRecordUpsert) SetUserID(v int64) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateUserID() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CheckinRecordUpsert) AddUserID(v int64) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldUserID, v)
	return u
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinRecordUpsert) SetCheckinDate(v string) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldCheckinDate, v)
	return u
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateCheckinDate() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldCheckinDate)
	return u
}

// SetAmountAwarded sets the "amount_awarded" field.
func (u *CheckinRecordUpsert) SetAmountAwarded(v float64) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldAmountAwarded, v)
	return u
}

// UpdateAmountAwarded sets the "amount_awarded" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateAmountAwarded() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldAmountAwarded)
	return u
}

// AddAmountAwarded adds v to the "amount_awarded" field.
func (u *CheckinRecordUpsert) AddAmountAwarded(v float64) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldAmountAwarded, v)
	return u
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinRecordUpsert) SetStreakDays(v int) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldStreakDays, v)
	return u
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateStreakDays() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldStreakDays)
	return u
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinRecordUpsert) AddStreakDays(v int) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldStreakDays, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinRecordUpsertOne) UpdateNewValues() *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkinrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckinRecordUpsertOne) Ignore() *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinRecordUpsertOne) DoNothing() *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinRecordCreate.OnConflict
// documentation for more info.
func (u *CheckinRecordUpsertOne) Update(set func(*CheckinRecordUpsert)) *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinRecordUpsertOne) SetUserID(v int64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CheckinRecordUpsertOne) AddUserID(v int64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateUserID() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinRecordUpsertOne) SetCheckinDate(v string) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateCheckinDate() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetAmountAwarded sets the "amount_awarded" field.
func (u *CheckinRecordUpsertOne) SetAmountAwarded(v float64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetAmountAwarded(v)
	})
}

// AddAmountAwarded adds v to the "amount_awarded" field.
func (u *CheckinRecordUpsertOne) AddAmountAwarded(v float64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddAmountAwarded(v)
	})
}

// UpdateAmountAwarded sets the "amount_awarded" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateAmountAwarded() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateAmountAwarded()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinRecordUpsertOne) SetStreakDays(v int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinRecordUpsertOne) AddStreakDays(v int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateStreakDays() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateStreakDays()
	})
}

// Exec executes the query.
func (u *CheckinRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckinRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckinRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckinRecordCreateBulk is the builder for creating many CheckinRecord entities in bulk.
type CheckinRecordCreateBulk struct {
	config
	err      error
	builders []*CheckinRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckinRecord entities in the database.
func (_c *CheckinRecordCreateBulk) Save(ctx context.Context) ([]*CheckinRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckinRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckinRecordCreateBulk) SaveX(ctx context.Context) []*CheckinRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckinRecordUpsertBulk {
	_c.conflict = opts
	return &CheckinRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinRecordCreateBulk) OnConflictColumns(columns ...string) *CheckinRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinRecordUpsertBulk{
		create: _c,
	}
}

// CheckinRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckinRecord nodes.
type CheckinRecordUpsertBulk struct {
	create *CheckinRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinRecordUpsertBulk) UpdateNewValues() *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkinrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckinRecordUpsertBulk) Ignore() *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinRecordUpsertBulk) DoNothing() *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinRecordCreateBulk.OnConflict
// documentation for more info.
func (u *CheckinRecordUpsertBulk) Update(set func(*CheckinRecordUpsert)) *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinRecordUpsertBulk) SetUserID(v int64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CheckinRecordUpsertBulk) AddUserID(v int64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateUserID() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinRecordUpsertBulk) SetCheckinDate(v string) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateCheckinDate() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetAmountAwarded sets the "amount_awarded" field.
func (u *CheckinRecordUpsertBulk) SetAmountAwarded(v float64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetAmountAwarded(v)
	})
}

// AddAmountAwarded adds v to the "amount_awarded" field.
func (u *CheckinRecordUpsertBulk) AddAmountAwarded(v float64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddAmountAwarded(v)
	})
}

// UpdateAmountAwarded sets the "amount_awarded" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateAmountAwarded() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateAmountAwarded()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *CheckinRecordUpsertBulk) SetStreakDays(v int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *CheckinRecordUpsertBulk) AddStreakDays(v int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateStreakDays() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateStreakDays()
	})
}

// Exec executes the query.
func (u *CheckinRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckinRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
