// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
)

// CheckinRecord is the model entity for the CheckinRecord schema.
type CheckinRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 签到日，服务器本地日期 YYYY-MM-DD
	CheckinDate string `json:"checkin_date,omitempty"`
	// 本次发放的美元额度（users.balance 同口径）
	AmountAwarded float64 `json:"amount_awarded,omitempty"`
	// 连续签到天数（含当天）
	StreakDays int `json:"streak_days,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckinRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldAmountAwarded:
			values[i] = new(sql.NullFloat64)
		case checkinrecord.FieldID, checkinrecord.FieldUserID, checkinrecord.FieldStreakDays:
			values[i] = new(sql.NullInt64)
		case checkinrecord.FieldCheckinDate:
			values[i] = new(sql.NullString)
		case checkinrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckinRecord fields.
func (_m *CheckinRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case checkinrecord.FieldCheckinDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_date", values[i])
			} else if value.Valid {
				_m.CheckinDate = value.String
			}
		case checkinrecord.FieldAmountAwarded:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_awarded", values[i])
			} else if value.Valid {
				_m.AmountAwarded = value.Float64
			}
		case checkinrecord.FieldStreakDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field streak_days", values[i])
			} else if value.Valid {
				_m.StreakDays = int(value.Int64)
			}
		case checkinrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckinRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CheckinRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CheckinRecord.
// Note that you need to call CheckinRecord.Unwrap() before calling this method if this CheckinRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckinRecord) Update() *CheckinRecordUpdateOne {
	return NewCheckinRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckinRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckinRecord) Unwrap() *CheckinRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckinRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckinRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CheckinRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("checkin_date=")
	builder.WriteString(_m.CheckinDate)
	builder.WriteString(", ")
	builder.WriteString("amount_awarded=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountAwarded))
	builder.WriteString(", ")
	builder.WriteString("streak_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreakDays))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckinRecords is a parsable slice of CheckinRecord.
type CheckinRecords []*CheckinRecord
