// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
)

// OAuthClientCreate is the builder for creating a OAuthClient entity.
type OAuthClientCreate struct {
	config
	mutation *OAuthClientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *OAuthClientCreate) SetName(v string) *OAuthClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthClientCreate) SetClientID(v string) *OAuthClientCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *OAuthClientCreate) SetClientSecret(v string) *OAuthClientCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *OAuthClientCreate) SetRedirectUris(v string) *OAuthClientCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetNillableRedirectUris sets the "redirect_uris" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableRedirectUris(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetRedirectUris(*v)
	}
	return _c
}

// SetAllowLocalhost sets the "allow_localhost" field.
func (_c *OAuthClientCreate) SetAllowLocalhost(v bool) *OAuthClientCreate {
	_c.mutation.SetAllowLocalhost(v)
	return _c
}

// SetNillableAllowLocalhost sets the "allow_localhost" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableAllowLocalhost(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetAllowLocalhost(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *OAuthClientCreate) SetEnabled(v bool) *OAuthClientCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableEnabled(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *OAuthClientCreate) SetRemark(v string) *OAuthClientCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableRemark(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthClientCreate) SetCreatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableCreatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthClientCreate) SetUpdatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableUpdatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_c *OAuthClientCreate) Mutation() *OAuthClientMutation {
	return _c.mutation
}

// Save creates the OAuthClient in the database.
func (_c *OAuthClientCreate) Save(ctx context.Context) (*OAuthClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthClientCreate) SaveX(ctx context.Context) *OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthClientCreate) defaults() {
	if _, ok := _c.mutation.RedirectUris(); !ok {
		v := oauthclient.DefaultRedirectUris
		_c.mutation.SetRedirectUris(v)
	}
	if _, ok := _c.mutation.AllowLocalhost(); !ok {
		v := oauthclient.DefaultAllowLocalhost
		_c.mutation.SetAllowLocalhost(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := oauthclient.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := oauthclient.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthClientCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthClient.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "OAuthClient.client_secret"`)}
	}
	if v, ok := _c.mutation.ClientSecret(); ok {
		if err := oauthclient.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		return &ValidationError{Name: "redirect_uris", err: errors.New(`ent: missing required field "OAuthClient.redirect_uris"`)}
	}
	if _, ok := _c.mutation.AllowLocalhost(); !ok {
		return &ValidationError{Name: "allow_localhost", err: errors.New(`ent: missing required field "OAuthClient.allow_localhost"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "OAuthClient.enabled"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "OAuthClient.remark"`)}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := oauthclient.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthClient.updated_at"`)}
	}
	return nil
}

func (_c *OAuthClientCreate) sqlSave(ctx context.Context) (*OAuthClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthClientCreate) createSpec() (*OAuthClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthclient.Table, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(oauthclient.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeString, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.AllowLocalhost(); ok {
		_spec.SetField(oauthclient.FieldAllowLocalhost, field.TypeBool, value)
		_node.AllowLocalhost = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(oauthclient.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(oauthclient.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthClient.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthClientUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthClientCreate) OnConflict(opts ...sql.ConflictOption) *OAuthClientUpsertOne {
	_c.conflict = opts
	return &OAuthClientUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthClientCreate) OnConflictColumns(columns ...string) *OAuthClientUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthClientUpsertOne{
		create: _c,
	}
}

type (
	// OAuthClientUpsertOne is the builder for "upsert"-ing
	//  one OAuthClient node.
	OAuthClientUpsertOne struct {
		create *OAuthClientCreate
	}

	// OAuthClientUpsert is the "OnConflict" setter.
	OAuthClientUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *OAuthClientUpsert) SetName(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateName() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldName)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsert) SetClientID(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientID() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientID)
	return u
}

// SetClientSecret sets the "client_secret" field.
func (u *OAuthClientUpsert) SetClientSecret(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientSecret, v)
	return u
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientSecret() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientSecret)
	return u
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsert) SetRedirectUris(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldRedirectUris, v)
	return u
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateRedirectUris() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldRedirectUris)
	return u
}

// SetAllowLocalhost sets the "allow_localhost" field.
func (u *OAuthClientUpsert) SetAllowLocalhost(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowLocalhost, v)
	return u
}

// UpdateAllowLocalhost sets the "allow_localhost" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowLocalhost() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowLocalhost)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *OAuthClientUpsert) SetEnabled(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateEnabled() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldEnabled)
	return u
}

// SetRemark sets the "remark" field.
func (u *OAuthClientUpsert) SetRemark(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateRemark() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldRemark)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsert) SetUpdatedAt(v time.Time) *OAuthClientUpsert {
	u.Set(oauthclient.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateUpdatedAt() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthClientUpsertOne) UpdateNewValues() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthclient.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthClientUpsertOne) Ignore() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthClientUpsertOne) DoNothing() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthClientCreate.OnConflict
// documentation for more info.
func (u *OAuthClientUpsertOne) Update(set func(*OAuthClientUpsert)) *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OAuthClientUpsertOne) SetName(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateName() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateName()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsertOne) SetClientID(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientID() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientID()
	})
}

// SetClientSecret sets the "client_secret" field.
func (u *OAuthClientUpsertOne) SetClientSecret(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientSecret(v)
	})
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientSecret() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientSecret()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsertOne) SetRedirectUris(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateRedirectUris() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowLocalhost sets the "allow_localhost" field.
func (u *OAuthClientUpsertOne) SetAllowLocalhost(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowLocalhost(v)
	})
}

// UpdateAllowLocalhost sets the "allow_localhost" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowLocalhost() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowLocalhost()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OAuthClientUpsertOne) SetEnabled(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateEnabled() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *OAuthClientUpsertOne) SetRemark(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateRemark() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRemark()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsertOne) SetUpdatedAt(v time.Time) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateUpdatedAt() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OAuthClientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthClientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthClientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthClientUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthClientUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthClientCreateBulk is the builder for creating many OAuthClient entities in bulk.
type OAuthClientCreateBulk struct {
	config
	err      error
	builders []*OAuthClientCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthClient entities in the database.
func (_c *OAuthClientCreateBulk) Save(ctx context.Context) ([]*OAuthClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) SaveX(ctx context.Context) []*OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthClient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthClientUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthClientCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthClientUpsertBulk {
	_c.conflict = opts
	return &OAuthClientUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthClientCreateBulk) OnConflictColumns(columns ...string) *OAuthClientUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthClientUpsertBulk{
		create: _c,
	}
}

// OAuthClientUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthClient nodes.
type OAuthClientUpsertBulk struct {
	create *OAuthClientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthClientUpsertBulk) UpdateNewValues() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthclient.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthClientUpsertBulk) Ignore() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthClientUpsertBulk) DoNothing() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthClientCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthClientUpsertBulk) Update(set func(*OAuthClientUpsert)) *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OAuthClientUpsertBulk) SetName(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateName() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateName()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsertBulk) SetClientID(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientID() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientID()
	})
}

// SetClientSecret sets the "client_secret" field.
func (u *OAuthClientUpsertBulk) SetClientSecret(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientSecret(v)
	})
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientSecret() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientSecret()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsertBulk) SetRedirectUris(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateRedirectUris() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowLocalhost sets the "allow_localhost" field.
func (u *OAuthClientUpsertBulk) SetAllowLocalhost(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowLocalhost(v)
	})
}

// UpdateAllowLocalhost sets the "allow_localhost" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowLocalhost() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowLocalhost()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OAuthClientUpsertBulk) SetEnabled(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateEnabled() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *OAuthClientUpsertBulk) SetRemark(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateRemark() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRemark()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsertBulk) SetUpdatedAt(v time.Time) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateUpdatedAt() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OAuthClientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthClientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthClientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthClientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
